sonar.sources=backend/app,frontend/lib
sonar.tests=backend/tests,frontend/test
sonar.exclusions=**/.venv/**,**/.dart_tool/**,**/build/**,**/android/**,**/ios/**,**/linux/**,**/macos/**,**/windows/**,**/web/**,**/__pycache__/**,**/*.g.dart
